<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dosen')->insert([
            // Program Studi 1
            [
                'user_id' => 11,
                'nama_dosen' => 'Riyadi Purwanto, S.T., M.Eng.',
                'nip' => '198503182019031013',
                'tempat_lahir' => 'Purwokerto',
                'tanggal_lahir' => '1985-03-18',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 12,
                'nama_dosen' => 'Dwi Novia Prasetyanti, S.Kom., M.Cs.',
                'nip' => '197911192021212009',
                'tempat_lahir' => 'Wonogiri',
                'tanggal_lahir' => '1979-11-19',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Super Admin',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 13,
                'nama_dosen' => 'Cahya Vikasari, S.T., M.Eng.',
                'nip' => '198412012018032001',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1984-12-01',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Koordinator Program Studi',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 14,
                'nama_dosen' => 'Antonius Agung Hartono, S.T., M.Eng.',
                'nip' => '198106152021211010',
                'tempat_lahir' => 'Klaten',
                'tanggal_lahir' => '1981-06-15',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 15,
                'nama_dosen' => 'Lutfi Syafirullah, S.T., M.Kom.',
                'nip' => '05.16.8018',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1984-11-21',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 16,
                'nama_dosen' => 'Prih Diantono Abda`u, S.Kom., M.Kom.',
                'nip' => '199008082019031017',
                'tempat_lahir' => 'Demak',
                'tanggal_lahir' => '1990-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 17,
                'nama_dosen' => 'Andesita Prihantara, S.T., M.Eng.',
                'nip' => '198405072019031011',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-05-07',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 18,
                'nama_dosen' => 'Nur Wahyu Rahadi, S.Kom., M.Eng.',
                'nip' => '198105092021211004',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1981-05-09',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 19,
                'nama_dosen' => 'Annas Setiawan Prabowo, S.Kom., M.Eng.',
                'nip' => '198711172018031001',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1987-11-17',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 20,
                'nama_dosen' => 'Rostika Listyaningrum, S.Si., M.Si.',
                'nip' => '198308222021212003',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1983-08-22',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 21,
                'nama_dosen' => 'Laura Sari, S.Si., M.Sc.',
                'nip' => '198809132019032012',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1988-09-13',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            [
                'user_id' => 22,
                'nama_dosen' => 'Annisa Romadloni, S.Hum., M.A.',
                'nip' => '198605142019032008',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1986-05-14',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 1,
            ],
            // Program Studi 2
            [
                'user_id' => 23,
                'nama_dosen' => 'Abdul Rohman Supriyono, S.T., M.Kom.',
                'nip' => '09.10.3008',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '1984-05-15',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Koordinator Program Studi',
                'program_studi_id' => 2,
            ],
            [
                'user_id' => 24,
                'nama_dosen' => 'Muhammad Nur Faiz, S.Kom., M.Kom.',
                'nip' => '199303242019031011',
                'tempat_lahir' => 'Pekalongan',
                'tanggal_lahir' => '1993-03-24',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 2,
            ],
            [
                'user_id' => 25,
                'nama_dosen' => 'Linda Perdana Wanti, S.Kom., M.Kom.',
                'nip' => '198810102019032020',
                'tempat_lahir' => 'Magelang',
                'tanggal_lahir' => '1988-10-10',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 2,
            ],
            [
                'user_id' => 26,
                'nama_dosen' => 'Oman Somantri, S.Kom., M.Kom.',
                'nip' => '198506272019031006',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '1985-06-27',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 2,
            ],
            [
                'user_id' => 27,
                'nama_dosen' => 'Ratih Hafsarah Maharani, S.Kom., M.Kom.',
                'nip' => '198509172019032015',
                'tempat_lahir' => 'Kudus',
                'tanggal_lahir' => '1985-09-17',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 2,
            ],

            // Program Studi 3
            [
                'user_id' => 28,
                'nama_dosen' => 'Nur Wachid Adi Prasetya, S.Kom., M.Kom.',
                'nip' => '198811152019031008',
                'tempat_lahir' => 'Kebumen',
                'tanggal_lahir' => '1988-11-15',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Koordinator Program Studi',
                'program_studi_id' => 3,
            ],
            [
                'user_id' => 29,
                'nama_dosen' => 'Isa Bahroni, S.Kom, M.Eng',
                'nip' => '196611212021211002',
                'tempat_lahir' => 'Pemalang',
                'tanggal_lahir' => '1966-11-21',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 3,
            ],
            [
                'user_id' => 30,
                'nama_dosen' => 'Agus Susanto, S.Kom., M.Kom.',
                'nip' => '199109162019031013',
                'tempat_lahir' => 'Tegal',
                'tanggal_lahir' => '1991-09-16',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 3,
            ],
            [
                'user_id' => 31,
                'nama_dosen' => 'Santi Purwaningrum, S.Kom., M.Kom.',
                'nip' => '199307142019032026',
                'tempat_lahir' => 'Blora',
                'tanggal_lahir' => '1993-07-14',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 3,
            ],

            // Program Studi 4
            [
                'user_id' => 32,
                'nama_dosen' => 'Faidzin Firdaus',
                'nip' => '197912062010121001',
                'tempat_lahir' => 'Purworejo',
                'tanggal_lahir' => '1979-12-06',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Koordinator Program Studi',
                'program_studi_id' => 4,
            ],
            [
                'user_id' => 33,
                'nama_dosen' => 'Ganjar Ndaru Ikhtiagung, S.E., M.M.',
                'nip' => '198307282021211002',
                'tempat_lahir' => 'Jepara',
                'tanggal_lahir' => '1983-07-28',
                'jenis_kelamin' => 'Laki-laki',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 4,
            ],
            [
                'user_id' => 34,
                'nama_dosen' => 'Hety Dwi Hastuti, S.E., M.Si.',
                'nip' => '198803312019032017',
                'tempat_lahir' => 'Sragen',
                'tanggal_lahir' => '1988-03-31',
                'jenis_kelamin' => 'Perempuan',
                'jabatan' => 'Dosen Biasa',
                'program_studi_id' => 4,
            ],
        ]);
    }
}
