<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Maria Ine',
                'email' => 'maria@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puput Era',
                'email' => 'puput@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rayhan Afrizal',
                'email' => 'rayhan@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yefta Charrand',
                'email' => 'yefta@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gita Listiani',
                'email' => 'gita@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adisa Laras',
                'email' => 'adisa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daniel Fajar',
                'email' => 'daniel@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fardan Nur',
                'email' => 'fardan@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arif Nur',
                'email' => 'arif@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ratna Winingsih',
                'email' => 'ratna@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Dosen (user_id: 11 - 20)
            // [
            //     'name' => 'Prih Diantono',
            //     'email' => 'prih@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Cahya Vikasari',
            //     'email' => 'cahya@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Lutfi Syafirullah',
            //     'email' => 'lutfi@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Abdul Rohman',
            //     'email' => 'abdul@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Nur Wachid',
            //     'email' => 'nur@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Annas Setiawan',
            //     'email' => 'faidzin@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Antonius Agung',
            //     'email' => 'antonius@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Fajar Mahardika',
            //     'email' => 'fajar@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Dwi Novia',
            //     'email' => 'dwi@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Isa Bahroni',
            //     'email' => 'isa@gmail.com',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('11111111'),
            //     'role' => 'Dosen',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            [
                'name' => 'Riyadi Purwanto, S.T., M.Eng.',
                'email' => 'riyadi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dwi Novia Prasetyanti, S.Kom., M.Cs.',
                'email' => 'dwi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_dosen' => 'Cahya Vikasari, S.T., M.Eng.',
                'email' => 'cahya@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_dosen' => 'Antonius Agung Hartono, S.T., M.Eng.',
                'email' => 'antonius@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_dosen' => 'Lutfi Syafirullah, S.T., M.Kom.',
                'email' => 'lutfi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_dosen' => 'Prih Diantono Abda`u, S.Kom., M.Kom.',
                'email' => 'prih@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andesita Prihantara, S.T., M.Eng.',
                'email' => 'andesita@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nur Wahyu Rahadi, S.Kom., M.Eng.',
                'email' => 'nur@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Annas Setiawan Prabowo, S.Kom., M.Eng.',
                'email' => 'annas@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rostika Listyaningrum, S.Si., M.Si.',
                'email' => 'rostika@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laura Sari, S.Si., M.Sc.',
                'email' => 'laura@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Annisa Romadloni, S.Hum., M.A.',
                'email' => 'annisa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Abdul Rohman Supriyono',
                'email' => 'abdul@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Nur Faiz',
                'email' => 'muhammad@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Linda Perdana Wanti',
                'email' => 'linda@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oman Somantri',
                'email' => 'oman@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ratih Hafsarah Maharani',
                'email' => 'ratih@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nur Wachid Adi Prasetya',
                'email' => 'wachid@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isa Bahroni',
                'email' => 'isa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agus Susanto',
                'email' => 'agus@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Santi Purwaningrum',
                'email' => 'santi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Faidzin Firdaus',
                'email' => 'faidzin@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ganjar Ndaru Ikhtiagung',
                'email' => 'ganjar@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hety Dwi Hastuti',
                'email' => 'hety@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11111111'),
                'role' => 'Dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
